name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
    
    - name: Clone the repository
      run: |
        git clone https://bulletdev/pipeline-automatizador.git
        cd pipeline-automatizer
    
    - name: Compile the project
      run: javac PipelineConfigApp.java
    
    - name: Run the application
      run: java PipelineConfigApp
