name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'
        java-package: 'jdk'
        architecture: 'x64'
        check-latest: false
        server-id: 'github'
        server-username: '${{ github.actor }}'
        server-password: '${{ secrets.GITHUB_TOKEN }}'
        overwrite-settings: true

    - name: Clone the repository
      run: git clone https://github.com/bulletdev/pipeline-automatizador.git

    - name: Navigate to repository directory
      working-directory: pipeline-automatizador
      run: ls -la 

    - name: Compile the project
      working-directory: pipeline-automatizador
      run: javac PipelineConfigApp.java

    - name: Run the application
      working-directory: pipeline-automatizador
      run: java PipelineConfigApp
